/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Card: typeof import('primevue/card')['default']
    copy: typeof import('./src/components/ThreadPreview copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MenuBars: typeof import('./src/components/MenuBars.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thread: typeof import('./src/components/Thread.vue')['default']
    ThreadPreview: typeof import('./src/components/ThreadPreview.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
